/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.sch.elib.view;

import id.sch.elib.controller.PenerbitController;
import id.sch.elib.model.Penerbit;
import id.sch.elib.util.DataLibrary;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rizky.aditya
 */
public class ViewPenerbit extends javax.swing.JInternalFrame {

    private PenerbitController penerbitController;
    private DefaultTableModel tableModel;
    private ArrayList<Penerbit> masterPenerbitList;
    private ArrayList<Penerbit> penerbitList;
    private ArrayList<String> columnName;
    private boolean editMode;
    private Penerbit penerbitModel;
    
    protected static boolean inputBukuMode;

    /**
     * Creates new form ViewPenerbit
     */
    public ViewPenerbit() {
        initComponents();
        reInitValiables();

        tableList.setAutoCreateRowSorter(true);
        penerbitController = new PenerbitController();
        columnName = new ArrayList<String>();
        columnName.add("Nama");
        columnName.add("Alamat");
        columnName.add("Kota");
        columnName.add("Telepon");

        //set search column by
        searchColumnCb.removeAllItems();
        for (int i = 0; i < columnName.size(); i++) {
            searchColumnCb.addItem(columnName.get(i));
        }

        //set table value
        masterPenerbitList = penerbitController.fetchData(masterPenerbitList, false);
        System.out.println("test#1 " + masterPenerbitList.size());
        penerbitList = masterPenerbitList;
        setTableValue();
    }

    public void setTableValue() {
        tableModel = new DefaultTableModel(columnName.toArray(), penerbitList.size());
        tableList.setModel(tableModel);
        for (int i = 0; i < penerbitList.size(); i++) {
            tableList.setValueAt(penerbitList.get(i).getNamaPenerbit(), i, 0);
            tableList.setValueAt(penerbitList.get(i).getAlamatPenerbit(), i, 1);
            tableList.setValueAt(penerbitList.get(i).getKotaPenerbit(), i, 2);
            tableList.setValueAt(penerbitList.get(i).getTelponPenerbit(), i, 3);
        }
    }

    public void resetAllFieldInput() {
        namaPenerbit.setText("");
        alamatPenerbit.setText("");
        kotaPenerbit.setText("");
        teleponPenerbit.setText("");
    }

    public void reInitValiables() {
        penerbitModel = new Penerbit();
        editMode = false;
        editButton.setSelected(editMode);
        editButton.setText("Edit Record");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchColumnCb = new javax.swing.JComboBox();
        searchValue = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableList = new javax.swing.JTable();
        editButton = new javax.swing.JToggleButton();
        deleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        namaPenerbit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alamatPenerbit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kotaPenerbit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teleponPenerbit = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("List Penerbit");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Searching Panel"));

        jLabel1.setText("Search by");

        searchColumnCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchColumnCb, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(searchColumnCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchBtn))
        );

        tableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableList);

        editButton.setText("jToggleButton1");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Record");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Panel"));

        jLabel3.setText("Nama Penerbit");

        jLabel4.setText("Alamat");

        jLabel5.setText("Kota");

        jLabel6.setText("Telepon");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setText("Reset");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teleponPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(namaPenerbit)
                                .addComponent(alamatPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(kotaPenerbit)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamatPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kotaPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(teleponPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        penerbitList = new ArrayList<Penerbit>();
        String searchCol = searchColumnCb.getSelectedItem().toString();
        String searchParam = searchValue.getText();
        System.out.println("param " + searchParam);
        System.out.println("search col " + searchCol);
        if (!searchParam.equals("")) {
            penerbitList = penerbitController.search(masterPenerbitList, searchParam, searchCol);
        } else {
            penerbitList = masterPenerbitList;
        }
        System.out.println("SIZE MASTER " + masterPenerbitList.size());
        System.out.println("SIZE LIST " + penerbitList.size());
        setTableValue();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String nama = namaPenerbit.getText();
        String alamat = alamatPenerbit.getText();
        String kota = kotaPenerbit.getText();
        String telpon = teleponPenerbit.getText();
        if (!nama.equals("") && !alamat.equals("") && !kota.equals("") && !telpon.equals("")) {
            penerbitModel.setNamaPenerbit(nama);
            penerbitModel.setAlamatPenerbit(alamat);
            penerbitModel.setKotaPenerbit(kota);
            penerbitModel.setTelponPenerbit(telpon);
            penerbitModel.setActive(true);
            penerbitModel.setUserInput(DataLibrary.getInstance().getUser().getUsername());

            penerbitController.setPenerbitModel(penerbitModel);
            penerbitController.setEditMode(editMode);
            String message = penerbitController.save();
            if (!message.equals("success")) {
                JOptionPane.showMessageDialog(null, (editMode ? "Update" : "Submit") + " data gagal", "Submit Data Error", JOptionPane.ERROR_MESSAGE);
            }
            resetAllFieldInput();
            reInitValiables();

            //refresh table
            masterPenerbitList = penerbitController.fetchData(masterPenerbitList, true);
            penerbitList = masterPenerbitList;
            setTableValue();
            if(inputBukuMode){
                InputBuku inputBuku = InputBuku.getInstance(false);
                inputBuku.setPenerbitItem(false);
                inputBuku.penerbitCmb.setSelectedIndex(masterPenerbitList.size()-1);
                inputBukuMode = false;
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "One or more field is empty, Cannot insert data", "INPUT-ERROR", 0);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        resetAllFieldInput();
    }//GEN-LAST:event_cancelActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if (editButton.isSelected()) {
            editButton.setText("Cancel Edit");
            editMode = true;
            penerbitModel = penerbitList.get(tableList.getSelectedRow());

            namaPenerbit.setText(penerbitModel.getNamaPenerbit());
            alamatPenerbit.setText(penerbitModel.getAlamatPenerbit());
            kotaPenerbit.setText(penerbitModel.getKotaPenerbit());
            teleponPenerbit.setText(penerbitModel.getTelponPenerbit());
        } else {
            editButton.setText("Edit Record");
            editMode = false;
            penerbitModel = new Penerbit();
            tableList.clearSelection();
            resetAllFieldInput();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure want to delete selected record?", "Delete Record",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            penerbitModel = penerbitList.get(tableList.getSelectedRow());
            penerbitModel.setActive(false);
            penerbitModel.setUserInput(DataLibrary.getInstance().getUser().getUsername());
            editMode = true;
            penerbitController.setPenerbitModel(penerbitModel);
            penerbitController.setEditMode(editMode);
            penerbitController.save();

            //reset table
            tableList.clearSelection();
            penerbitList = penerbitController.fetchData(masterPenerbitList, true);
            setTableValue();
            resetAllFieldInput();
            reInitValiables();
        } else {
            tableList.clearSelection();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatPenerbit;
    private javax.swing.JButton cancel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JToggleButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kotaPenerbit;
    private javax.swing.JTextField namaPenerbit;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox searchColumnCb;
    private javax.swing.JTextField searchValue;
    private javax.swing.JButton submit;
    private javax.swing.JTable tableList;
    private javax.swing.JTextField teleponPenerbit;
    // End of variables declaration//GEN-END:variables
}
